-- 배치 SQL: 테이블 → 테이블 컬럼 매핑 (FR-SQ-04, COL_DERIVES)

-- 컬럼 목록 없는 INSERT … SELECT: 카탈로그 컬럼 순서로 위치 짝
INSERT INTO ORDER_HIST
SELECT ORDER_ID, CUST_ID, AMOUNT FROM ORDERS WHERE STATUS = 'C';

-- CTAS: 이후 SQL에서 카탈로그처럼 사용
CREATE TABLE VIP_CUST AS
SELECT c.CUST_ID, CUST_NAME, CUST_GRADE GRADE FROM CUSTOMER c WHERE CUST_GRADE = 'A';

INSERT INTO VIP_REPORT (CUST_ID, GRADE)
SELECT CUST_ID, GRADE FROM VIP_CUST;

-- MERGE: 집계 결과를 요약 테이블로
MERGE INTO CUST_SUMMARY t
USING (SELECT CUST_ID, SUM(AMOUNT) TOTAL FROM ORDERS GROUP BY CUST_ID) s
   ON (t.CUST_ID = s.CUST_ID)
 WHEN MATCHED THEN UPDATE SET t.TOTAL_AMT = s.TOTAL
 WHEN NOT MATCHED THEN INSERT (CUST_ID, TOTAL_AMT) VALUES (s.CUST_ID, s.TOTAL);
