-- 카탈로그 스냅샷 (FR-SQ-01): 컬럼 순서 유지
CREATE TABLE ORDERS (ORDER_ID NUMBER, CUST_ID VARCHAR2(10), AMOUNT NUMBER, STATUS CHAR(1));
CREATE TABLE CUSTOMER (CUST_ID VARCHAR2(10), CUST_NAME VARCHAR2(50), CUST_GRADE CHAR(1));
CREATE TABLE ORDER_HIST (ORDER_ID NUMBER, CUST_ID VARCHAR2(10), AMOUNT NUMBER);
CREATE TABLE CUST_SUMMARY (CUST_ID VARCHAR2(10), TOTAL_AMT NUMBER);
CREATE TABLE VIP_REPORT (CUST_ID VARCHAR2(10), GRADE CHAR(1));
